import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/landing/header";
import { Open_Sans, Raleway } from "next/font/google";

export const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-body",
  weight: ["400", "700"],
});

export const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${openSans.variable} ${raleway.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-background text-white">
        <Header />
        {children}
      </body>
    </html>
  );
}
